Unstub langage object in EntityHandler
We have been seeing failures in Wikibase Secondary CI since March 25.,
with the error:

```
TypeError: MediaWiki\Linker\LinkRenderer::makeRedirectHeader():
Argument #1 ($lang) must be of type MediaWiki\Language\Language,
MediaWiki\StubObject\StubUserLang given, called in
extensions/Wikibase/repo/includes/Content/EntityHandler.php
on line 829
```

This does not seem to be directly connected to a change in our code.
Nevertheless, calling `StubUserLang::unstub` here seems to resolve
the issue. A similar pattern can be seen in Mediawiki core for the
global `$wgLang` object.

Unstub `$wgLang` before returning it in the EntityHandler.

Bug: T421231
Change-Id: I01eccdbf9f87b02f14e4735d290b9e356a6a6964